---
title: "RIS June Project Update"
author: "Fonti Kar + Daniel Falster"
date: "27-June-2024"
format: 
  html:
    theme: lumen
    toc: true
    embed-resources: true
editor: source
from: markdown+emoji
bootswatch: true
---

## Hey folks! :wave:

Hope everyone's T2 started out smoothly. Another 3 months have flown by and here we our quarterly update!

## Summary

-   We ditched [Posit Connect](https://posit.co/products/enterprise/connect/) and migrated to [shinyapps.io](https://www.shinyapps.io/)
-   Please submit your availability [in this timeline](https://unsw-my.sharepoint.com/:x:/r/personal/z3516573_ad_unsw_edu_au1/Documents/UNSW_RIS_2022/RIS_project_planning.xlsx?d=wd594d67bda574876a85c632e9eedd6ae&csf=1&web=1&e=DpItgk) for T1 and T2

## Group decisions :busts_in_silhouette:

### Shiny hosting :globe_with_meridians:

-   We hold a [Posit Connect](https://posit.co/products/enterprise/connect/) license (expires on 26 June) for deploying our Shiny apps. Originally, our plan was to purchase an in-house server for run Posit Connect and apps but this posed a security risk to UNSW infrastructure.
-   I've been working with Michael Grogan (Intersect/ResTech) to set up a virtual instance from [NECTAR](https://dashboard.rc.nectar.org.au/auth/login/) as an alternative solution (AUD \$10.77 / day, 8 vcpu 16GB RAM, \$1447 in total).
-   I had some unexpectedly complicated discussions with Posit about the lack of suitability of the Posit Connect license to our project. In a nutshell, we were sold an enterprise level license which is an overkill for our projects' needs. Unfortunately, Posit cannot do anything about the license.

### Our plan :chart_with_upwards_trend:

-   We will cut our losses with our Posit Connect license and migrate to a Professional [shinyapps.io](https://www.shinyapps.io/) account (USD \$3860 / year or \$349 / month) and not worry about setting our own virtual instance altogether.

-   Our domain looks like this: <https://unsw.shinyapps.io/infinitylists/>

## Project updates (Nov 23 - Feb 24)

### Software :rocket:

-   Shiny testing for [`APCalign-app`](https://unsw.shinyapps.io/APCalign-app/) (Falster + Cornwell)
-   Unit testing for [`infinitylists`](https://unsw.shinyapps.io/infinitylists/)
-   Started the Work-in-progress [blog](https://unsw-edu-au.github.io/wip-blog/)
-   Created foundations for [`AugGaussian`](https://github.com/fontikar/augGauss) package (Lee)
-   Upgraded `ecoCopula` package (Warton)
-   Assisted with scoping for 'automated data analyses' (Sisson)
-   Assisted with `groc` package (Lafaye)
-   Created foundations for [`MAGPI-HiVis`](https://github.com/MagpiSurvey/MAGP-HiVis) app (Foster)

### In progress :construction:

-   [`MAGPI-HiVis`](https://github.com/MagpiSurvey/MAGP-HiVis) app (Foster)
-   [`ecopower`](https://github.com/eco-stats/ecopower) package (Warton)
-   [`rmot`](https://github.com/traitecoevo/rmot) package (Falster + Warton)
-   CI/CD workflow for modelevalution.org outputs (Abramowitz)
-   R research training resource for Psychology (Williams)

## What's next (Mar 24 - Jul 24)

### Software :package:

#### Plan ahead :dart:

Dates in brackets indicate estimated finished date

-   R research training resource for Psychology (Williams) (End of May)
-   CI/CD workflow for modelevalution.org outputs (Abramowitz) (End of May)
-   [`rmot`](https://github.com/traitecoevo/rmot) package (Falster + Warton) (Mid April)
-   [`ecopower`](https://github.com/eco-stats/ecopower) package (Warton) (End of March)
-   [`MAGPI-HiVis`](https://github.com/MagpiSurvey/MAGP-HiVis) app (Foster) (End of April)

#### New projects

-   Upgrade `IndependenceTests` (Lafaye)
-   Quarto/Huge website for Artificial Intelligence (Falster)
-   Shiny workflow for searchable databases (Nakagawa)

### Community building + Research training :woman_teacher:

:email: Please reach out if you would like to run any research skill based training for your community/group

-   Vafaee Lab: 
  - DIY R package
  - Git with it
  - Convert code for collaboration 
-   Environmental Computing Github workshop (TBD)

## What I need from you :pray:

Can you all fill in your rough availability [in this timeline](https://unsw-my.sharepoint.com/:x:/r/personal/z3516573_ad_unsw_edu_au1/Documents/UNSW_RIS_2022/RIS_project_planning.xlsx?d=wd594d67bda574876a85c632e9eedd6ae&csf=1&web=1&e=DpItgk) for T1 and T2 so we can synchronise our schedules and work more closely!

:rotating_light::rotating_light: If your projects have firm due dates please let me know ASAP so I can rearrange my project plan and prioritise your project! 🚨🚨
